version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4173:80"

  mongo:
    image: mongo
    ports:
      - "27017:27017"